### ISSUE TITLE
Currency Conversion Issue 

### ISSUE THREAD

**Issue by mbekezm** [iammerus/paynow-whmcs#2]
Okay so when using this module, if the customer's account is set to USD (or any other currency except ZWL) ,

When the invoice is paid, let's say the invoice was USD $2 and the customer paid ZWL$200 on EcoCash as per the conversion rate, instead of the whmcs crediting USD $2 to the invoice WHMCS whmcs will credit USD$200 , add the $2 to the invoice then add USD$198 as credit to the customer's account. 

How can we solve this so that if the customer's account is in another currency it will credit the invoiced amount only without pushing the converted amount?

**Comment by mbekezm** [comment]
Is they anything we can do to resolve this?

**Comment by iammerus** [comment]
Hey @mbekezm. 

Thanks for bringing this bug to my attention. I think I've figured out why it was happening

**Comment by iammerus** [comment]
This has been resolved in PR #3. Closing this issue
